-- P1-06 T2 Hive 物理行数（自动生成，表名取自 spark-warehouse/<db>.db/* 目录）
SHOW DATABASES;
SHOW TABLES IN dw_ods;
SELECT 'dw_ods.ods_behavior_event' AS tbl, COUNT(*) AS row_cnt FROM dw_ods.ods_behavior_event;
SELECT 'dw_ods.ods_product_event' AS tbl, COUNT(*) AS row_cnt FROM dw_ods.ods_product_event;
SELECT 'dw_ods.ods_trade_event' AS tbl, COUNT(*) AS row_cnt FROM dw_ods.ods_trade_event;
SELECT 'dw_ods.ods_user_event' AS tbl, COUNT(*) AS row_cnt FROM dw_ods.ods_user_event;
SELECT 'dw_ods.ods_behavior_event' AS tbl, dt, COUNT(*) AS row_cnt FROM dw_ods.ods_behavior_event GROUP BY dt ORDER BY dt;
SELECT 'dw_ods.ods_product_event' AS tbl, dt, COUNT(*) AS row_cnt FROM dw_ods.ods_product_event GROUP BY dt ORDER BY dt;
SELECT 'dw_ods.ods_trade_event' AS tbl, dt, COUNT(*) AS row_cnt FROM dw_ods.ods_trade_event GROUP BY dt ORDER BY dt;
SELECT 'dw_ods.ods_user_event' AS tbl, dt, COUNT(*) AS row_cnt FROM dw_ods.ods_user_event GROUP BY dt ORDER BY dt;
SHOW TABLES IN dw_dwd;
SELECT 'dw_dwd.dwd_order_detail' AS tbl, COUNT(*) AS row_cnt FROM dw_dwd.dwd_order_detail;
SELECT 'dw_dwd.dwd_reject_record' AS tbl, COUNT(*) AS row_cnt FROM dw_dwd.dwd_reject_record;
SELECT 'dw_dwd.dwd_user_behavior_detail' AS tbl, COUNT(*) AS row_cnt FROM dw_dwd.dwd_user_behavior_detail;
SHOW TABLES IN dw_dim;
SELECT 'dw_dim.dim_product' AS tbl, COUNT(*) AS row_cnt FROM dw_dim.dim_product;
SELECT 'dw_dim.dim_user' AS tbl, COUNT(*) AS row_cnt FROM dw_dim.dim_user;
SHOW TABLES IN dw_dws;
SELECT 'dw_dws.dws_behavior_funnel_day' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_behavior_funnel_day;
SELECT 'dw_dws.dws_product_behavior_day' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_product_behavior_day;
SELECT 'dw_dws.dws_product_sale_day' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_product_sale_day;
SELECT 'dw_dws.dws_region_sale_day' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_region_sale_day;
SELECT 'dw_dws.dws_trade_day' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_trade_day;
SELECT 'dw_dws.dws_user_behavior_day' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_user_behavior_day;
SELECT 'dw_dws.dws_user_trade_period' AS tbl, COUNT(*) AS row_cnt FROM dw_dws.dws_user_trade_period;
SHOW TABLES IN dw_ads;
SELECT 'dw_ads.ads_active_trend' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_active_trend;
SELECT 'dw_ads.ads_active_trend__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_active_trend__staging;
SELECT 'dw_ads.ads_behavior_funnel' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_behavior_funnel;
SELECT 'dw_ads.ads_behavior_funnel__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_behavior_funnel__staging;
SELECT 'dw_ads.ads_data_quality' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_data_quality;
SELECT 'dw_ads.ads_data_quality__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_data_quality__staging;
SELECT 'dw_ads.ads_hot_product' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_hot_product;
SELECT 'dw_ads.ads_hot_product__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_hot_product__staging;
SELECT 'dw_ads.ads_operation_overview' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_operation_overview;
SELECT 'dw_ads.ads_operation_overview__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_operation_overview__staging;
SELECT 'dw_ads.ads_product_conversion' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_product_conversion;
SELECT 'dw_ads.ads_product_conversion__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_product_conversion__staging;
SELECT 'dw_ads.ads_sale_trend' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_sale_trend;
SELECT 'dw_ads.ads_sale_trend__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_sale_trend__staging;
SELECT 'dw_ads.ads_user_profile' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_user_profile;
SELECT 'dw_ads.ads_user_profile__staging' AS tbl, COUNT(*) AS row_cnt FROM dw_ads.ads_user_profile__staging;
