SELECT '### ods_counts' AS section;
SELECT 'ods_behavior_event' AS t, dt, COUNT(*) AS rows FROM dw_ods.ods_behavior_event GROUP BY dt;
SELECT 'ods_trade_event' AS t, dt, COUNT(*) AS rows FROM dw_ods.ods_trade_event GROUP BY dt;
SELECT 'ods_product_event' AS t, dt, COUNT(*) AS rows FROM dw_ods.ods_product_event GROUP BY dt;
SELECT 'ods_user_event' AS t, dt, COUNT(*) AS rows FROM dw_ods.ods_user_event GROUP BY dt;
SELECT '### dwd_counts' AS section;
SELECT 'dwd_user_behavior_detail' AS t, dt, COUNT(*) AS rows FROM dw_dwd.dwd_user_behavior_detail GROUP BY dt;
SELECT 'dwd_order_detail' AS t, dt, COUNT(*) AS rows FROM dw_dwd.dwd_order_detail GROUP BY dt;
SELECT 'dwd_reject_record' AS t, dt, COUNT(*) AS rows FROM dw_dwd.dwd_reject_record GROUP BY dt;
SELECT '### dws_trade_day (dt=20260901)' AS section;
SELECT dt, order_count, buyer_count, sale_amount, refund_amount, net_sale_amount, avg_order_value FROM dw_dws.dws_trade_day WHERE dt='20260901';
SELECT '### ads_formal (dt=20260901，正式分区只有 dt，快照维度在 __staging)' AS section;
SELECT dt, pv, uv, dau, order_count, sale_amount, net_sale_amount, avg_order_value, refund_rate, full_refund_rate FROM dw_ads.ads_operation_overview WHERE dt='20260901';
SELECT 'ads_behavior_funnel' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_behavior_funnel WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_hot_product' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_hot_product WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_product_conversion' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_product_conversion WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_sale_trend' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_sale_trend WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_active_trend' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_active_trend WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_user_profile' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_user_profile WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_operation_overview' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_operation_overview WHERE dt='20260901' GROUP BY dt;
SELECT 'ads_data_quality' AS t, dt, COUNT(*) AS rows FROM dw_ads.ads_data_quality WHERE dt='20260901' GROUP BY dt;
SELECT '### ads_staging (快照隔离：每次发布独立 snapshot_id 分区)' AS section;
SELECT 'ads_operation_overview__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_operation_overview__staging GROUP BY snapshot_id, dt;
SELECT 'ads_behavior_funnel__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_behavior_funnel__staging GROUP BY snapshot_id, dt;
SELECT 'ads_hot_product__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_hot_product__staging GROUP BY snapshot_id, dt;
SELECT 'ads_product_conversion__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_product_conversion__staging GROUP BY snapshot_id, dt;
SELECT 'ads_sale_trend__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_sale_trend__staging GROUP BY snapshot_id, dt;
SELECT 'ads_active_trend__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_active_trend__staging GROUP BY snapshot_id, dt;
SELECT 'ads_user_profile__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_user_profile__staging GROUP BY snapshot_id, dt;
SELECT 'ads_data_quality__staging' AS t, snapshot_id, dt, COUNT(*) AS rows FROM dw_ads.ads_data_quality__staging GROUP BY snapshot_id, dt;
SELECT '### quality (dt=20260901)' AS section;
SELECT * FROM dw_ads.ads_data_quality WHERE dt='20260901' ORDER BY rule_code;
SELECT '### partitions' AS section;
SHOW PARTITIONS dw_ads.ads_operation_overview;
