-- =====================================================================
-- V28: 追加一条质量规则定义 —— `DWS_UV_PV_INVARIANT`（F-57 / S3-25）
--
-- 依据（逐字）：设计 §12.3「质量12项」第 9 项 line 507「同过滤条件UV≤PV。」；
--   同节 line 512「每条规则记录作用域、阈值、版本、阶段、实际值、passed、原始/生效严重度。
--   付款 vs 订单、订单项公式、DWD/DWS 对账三者独立，不能用一个 AMOUNT_RECONCILE 覆盖。」
--   （指导书 §7 阶段 3 line 148「每个指标固定粒度、分子分母、时间窗口、金额/退款口径、
--     空值规则和版本」——「分子分母」对本项即 pv/uv 两列的来源必须同口径。）
--
-- 为什么**另立一码**而不是复用 V27 的 `ADS_UV_PV_INVARIANT`（实测事实）：
--   第 9 项在两个不同站点各成立一次，且两处的**表、粒度、分区维度**各不相同：
--     ① ADS 站点：`ads_operation_overview__staging`，一次聚合成**一行/分区**，快照隔离靠 snapshot_id；
--     ② DWS 站点：`dws_product_behavior_day`，按 `product_id × category_id` 分组**逐行**，
--        表上**没有** snapshot 维度（`LocalSchemaInitJob` 实测：`(product_id, category_id, pv, uv,
--        fav, cart, buy) PARTITIONED BY (dt)`）。
--   一处通过不能证明另一处通过（ADS 行成立与商品逐行成立是两次独立判定），
--   按 line 512「不同校验不得合并」必须各有一码；合并则任一处漏测都会被另一处的绿灯掩盖。
--   落地前该缺口登记于 S3-23 覆盖核对表的「遗留①」与本文件同期的 backlog 单元格：
--   `DwsSql.scala:96-97` 的 uv≤pv **在产质量门里没有任何守卫**（全仓
--   `git grep -E "uv *<=? *pv|pv *>=? *uv"` 只命中 S3-23 规格里的**注释**）。
--
-- 「同过滤条件」是本规则的**作用域判据**，不是修饰词（实测事实）：
--   `DwsSql.productBehaviorDay` 中
--     `pv = SUM(CASE WHEN b.behavior_type = 'view' THEN 1 ELSE 0 END)`、
--     `uv = COUNT(DISTINCT CASE WHEN b.behavior_type = 'view' THEN b.user_id END)`
--   —— 两列出自**同一个**过滤条件（同表 `dwd_user_behavior_detail` 别名 b、同 `b.dt = '$dt'`，
--   见该 SQL 的 `WHERE b.dt = '$dt'`），故 `uv ≤ pv` 是构造性不变量。该前提由
--   `DwsUvPvInvariantSpec` 的结构守卫用例静态钉住（生产 SQL 若把两列改成不同过滤条件，该用例即失败），
--   不是只写在注释里。
--
-- 为什么**新增迁移**而不是改 V19/V25/V26/V27：四者都是**已发布**的迁移（F-88 / F-43 / F-55 / S3-23），
--   其内容按硬约束不得再改（改已发布迁移 = 决策门③）。故按「一次迁移一件事」追加一条**只插一行**
--   的加性迁移。新规则码必须**先登记再产出**：§7.3.1 line 524 规定未登记规则码一律「停止发布并报
--   未登记规则」，若只加 Java 目录不落库，新码第一次产出结果就会被读侧判为未登记而整链翻红。
--
-- 本迁移做什么（可逐条核对，全文无第二条语句）：
--   1) `INSERT IGNORE` 一行 `(rule_code, version, source_scope, stage, severity, severity_mode,
--      threshold_json, enabled, effective_from, effective_to, checksum)`。
--   2) **不建表、不改列、不删行、不改任何既有行的档位或阈值**；对已手工登记过同键行的库幂等。
--
-- 档位为何是 BLOCKING（而不是 WARN/ERROR）：`dws_product_behavior_day` 是 `ads_hot_product`
--   （热搜热度 `1.0*LOG1P(pv)+…`，AdsSql 实测读本表 `pv/fav/cart/buy`）与 `ads_product_conversion`
--   （`b.uv AS pv_users`，实测直连）的**唯一直接来源**。一旦某商品 `uv > pv`，两列已明确取自
--   **不同过滤条件**，则商品热度、商品转化率（分母就是这里的两列）整体不可信，而暂存存在性、
--   关键列非空、金额不变量可能同时全绿 —— 只判非空与金额无法发现本类破坏。
--   `threshold_json` 留 NULL：不变量无阈值可调（放宽阈值 = 把口径破坏放行）。
--   设计 line 508「宽松口径异常不一概作为阻断规则」说的是第 10 项「支付/浏览用户比及 cohort
--   解释」这类**跨口径比率**，与本项的同口径不变量不是一回事，故不援引为放宽依据。
--
-- 空值规则为何由**本码自判**（与 V27 的 ADS 码不同，此处口径差异须留痕）：
--   ADS 站点上 `pv`/`uv` 的 NULL 有**直接**唯一所有者（`AdsQualityJob.keyPredicates` 对
--   `ads_operation_overview` 的谓词已含 `pv IS NULL OR uv IS NULL`，档位 BLOCKING），故 V27 让本码
--   不重复判定。DWS 站点**没有**这样的所有者：实测 `keyPredicates` 的键集**只覆盖 ADS 暂存表**，
--   对 `dws_product_behavior_day` 无任何谓词。按「唯一所有者原则」，本层空缺即由本码承担 ⇒
--   判据写成 `(pv IS NULL OR uv IS NULL OR uv > pv)`，任一列为 NULL 即不通过：三值逻辑下
--   `uv > pv` 在 NULL 时求值为 NULL，若不显式判 NULL，「两列整体未计算」会被静默放行
--   （不可证明的不变量不得放行）。
--
-- checksum 的算法（与 `QualityRuleDefinition#checksum()` 逐字节一致，不是另一套哈希）：
--   SHA-256( ruleCode \x1f version \x1f sourceScope \x1f stage \x1f severity \x1f
--            severityMode \x1f thresholdJson(缺省为空串) \x1f enabled(1/0) \x1f
--            effectiveFrom(缺省为空串) \x1f effectiveTo(缺省为空串) )
--   十六进制小写 64 字符；rationale 不参与（改错别字不应使指纹变化）。
--   本行输入 = `DWS_UV_PV_INVARIANT` \x1f 1 \x1f `*` \x1f `DWS` \x1f `BLOCKING` \x1f
--              `FIXED` \x1f `` \x1f 1 \x1f `` \x1f ``
--   ⇒ 该行 checksum 与 `QualityRuleCatalog.DEFAULT` 里同名定义的 `checksum()` 必须相等，
--     由 `QualityRuleVersionMigrationScriptTest` 逐行对账（零漂移）。
--   （本值由独立脚本按上述算法重算，并先用 V27 的 `ADS_UV_PV_INVARIANT` 已知值
--     2140ab3e…d296 反向验证算法复现一致，再算本行。）
--
-- rationale 继续留 NULL：依据文本的唯一所有者在 Java 目录（`QualityRuleCatalog` 的 rationale
--   字段）与 `RuleSeverity.rationale(String)`，本表只存契约（档位/模式/阈值/指纹）。
--
-- 【本迁移在真库上的执行状态：未执行】
--   按本泳道硬约束（DB 冻结：不起停服务、不对 3306 执行任何 DDL/DML），本脚本只入版本库，
--   未在任何正式库执行；「已在真库生效」不得由本文件推断。
-- =====================================================================

INSERT IGNORE INTO quality_rule_definition
    (rule_code, version, source_scope, stage, severity, severity_mode,
     threshold_json, enabled, effective_from, effective_to, checksum)
VALUES
    ('DWS_UV_PV_INVARIANT', 1, '*', 'DWS', 'BLOCKING', 'FIXED', NULL, 1, NULL, NULL,
     '6c61c21dcb2e5fe893e7965d28cf1f9f266af996a84f5a865f1341e070e41b09');
