SELECT 'zz_instance' AS k, '3306|85191145-1491-11f0-b4e2-60cf84d55629|dahaishui' AS v;
SELECT 'analytics_meta.ai_call_log.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.ai_call_log;
SELECT 'analytics_meta.ai_call_log.max_id' AS k, MAX(id) AS v FROM analytics_meta.ai_call_log;
SELECT 'analytics_meta.ai_call_log.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.ai_call_log;
SELECT 'analytics_meta.ai_call_log.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.ai_call_log WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.ai_query_history.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.ai_query_history;
SELECT 'analytics_meta.ai_query_history.max_id' AS k, MAX(id) AS v FROM analytics_meta.ai_query_history;
SELECT 'analytics_meta.ai_query_history.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.ai_query_history;
SELECT 'analytics_meta.ai_query_history.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.ai_query_history WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.data_quality_result.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.data_quality_result;
SELECT 'analytics_meta.data_quality_result.max_id' AS k, MAX(id) AS v FROM analytics_meta.data_quality_result;
SELECT 'analytics_meta.data_quality_result.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.data_quality_result;
SELECT 'analytics_meta.data_quality_result.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.data_quality_result WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_evaluation.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.decision_evaluation;
SELECT 'analytics_meta.decision_evaluation.max_id' AS k, MAX(id) AS v FROM analytics_meta.decision_evaluation;
SELECT 'analytics_meta.decision_evaluation.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.decision_evaluation;
SELECT 'analytics_meta.decision_evaluation.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_evaluation WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_task.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.max_id' AS k, MAX(id) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_task WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_task.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_task WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_task.max_started_at' AS k, MAX(started_at) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.inwin_started_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_task WHERE started_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_task.max_completed_at' AS k, MAX(completed_at) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.inwin_completed_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_task WHERE completed_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_task.max_evaluated_at' AS k, MAX(evaluated_at) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.inwin_evaluated_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_task WHERE evaluated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.decision_task.max_approved_at' AS k, MAX(approved_at) AS v FROM analytics_meta.decision_task;
SELECT 'analytics_meta.decision_task.inwin_approved_at' AS k, COUNT(*) AS v FROM analytics_meta.decision_task WHERE approved_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.file_checkpoint.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.file_checkpoint;
SELECT 'analytics_meta.file_checkpoint.max_id' AS k, MAX(id) AS v FROM analytics_meta.file_checkpoint;
SELECT 'analytics_meta.file_checkpoint.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.file_checkpoint;
SELECT 'analytics_meta.file_checkpoint.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.file_checkpoint WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.flyway_schema_history.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.flyway_schema_history;
SELECT 'analytics_meta.flyway_schema_history.max_installed_on' AS k, MAX(installed_on) AS v FROM analytics_meta.flyway_schema_history;
SELECT 'analytics_meta.flyway_schema_history.inwin_installed_on' AS k, COUNT(*) AS v FROM analytics_meta.flyway_schema_history WHERE installed_on BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.ingestion_batch.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.ingestion_batch;
SELECT 'analytics_meta.ingestion_batch.max_id' AS k, MAX(id) AS v FROM analytics_meta.ingestion_batch;
SELECT 'analytics_meta.ingestion_batch.max_start_time' AS k, MAX(start_time) AS v FROM analytics_meta.ingestion_batch;
SELECT 'analytics_meta.ingestion_batch.inwin_start_time' AS k, COUNT(*) AS v FROM analytics_meta.ingestion_batch WHERE start_time BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.ingestion_batch.max_end_time' AS k, MAX(end_time) AS v FROM analytics_meta.ingestion_batch;
SELECT 'analytics_meta.ingestion_batch.inwin_end_time' AS k, COUNT(*) AS v FROM analytics_meta.ingestion_batch WHERE end_time BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.metric_snapshot.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.metric_snapshot;
SELECT 'analytics_meta.metric_snapshot.max_id' AS k, MAX(id) AS v FROM analytics_meta.metric_snapshot;
SELECT 'analytics_meta.metric_snapshot.max_business_time' AS k, MAX(business_time) AS v FROM analytics_meta.metric_snapshot;
SELECT 'analytics_meta.metric_snapshot.inwin_business_time' AS k, COUNT(*) AS v FROM analytics_meta.metric_snapshot WHERE business_time BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.metric_snapshot.max_data_updated_at' AS k, MAX(data_updated_at) AS v FROM analytics_meta.metric_snapshot;
SELECT 'analytics_meta.metric_snapshot.inwin_data_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.metric_snapshot WHERE data_updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.metric_snapshot.max_published_at' AS k, MAX(published_at) AS v FROM analytics_meta.metric_snapshot;
SELECT 'analytics_meta.metric_snapshot.inwin_published_at' AS k, COUNT(*) AS v FROM analytics_meta.metric_snapshot WHERE published_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.metric_snapshot.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.metric_snapshot;
SELECT 'analytics_meta.metric_snapshot.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.metric_snapshot WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.metric_value.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.metric_value;
SELECT 'analytics_meta.metric_value.max_id' AS k, MAX(id) AS v FROM analytics_meta.metric_value;
SELECT 'analytics_meta.metric_value.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.metric_value;
SELECT 'analytics_meta.metric_value.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.metric_value WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.operation_audit_log.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.operation_audit_log;
SELECT 'analytics_meta.operation_audit_log.max_id' AS k, MAX(id) AS v FROM analytics_meta.operation_audit_log;
SELECT 'analytics_meta.operation_audit_log.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.operation_audit_log;
SELECT 'analytics_meta.operation_audit_log.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.operation_audit_log WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_run.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.max_id' AS k, MAX(id) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.max_business_time' AS k, MAX(business_time) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.inwin_business_time' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE business_time BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_run.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_run.max_started_at' AS k, MAX(started_at) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.inwin_started_at' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE started_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_run.max_finished_at' AS k, MAX(finished_at) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.inwin_finished_at' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE finished_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_run.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.pipeline_run;
SELECT 'analytics_meta.pipeline_run.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_stage_run.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_stage_run;
SELECT 'analytics_meta.pipeline_stage_run.max_id' AS k, MAX(id) AS v FROM analytics_meta.pipeline_stage_run;
SELECT 'analytics_meta.pipeline_stage_run.max_started_at' AS k, MAX(started_at) AS v FROM analytics_meta.pipeline_stage_run;
SELECT 'analytics_meta.pipeline_stage_run.inwin_started_at' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_stage_run WHERE started_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.pipeline_stage_run.max_finished_at' AS k, MAX(finished_at) AS v FROM analytics_meta.pipeline_stage_run;
SELECT 'analytics_meta.pipeline_stage_run.inwin_finished_at' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_stage_run WHERE finished_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.quarantine_record.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.quarantine_record;
SELECT 'analytics_meta.quarantine_record.max_id' AS k, MAX(id) AS v FROM analytics_meta.quarantine_record;
SELECT 'analytics_meta.quarantine_record.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.quarantine_record;
SELECT 'analytics_meta.quarantine_record.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.quarantine_record WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.runtime_profile.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.runtime_profile;
SELECT 'analytics_meta.runtime_profile.max_id' AS k, MAX(id) AS v FROM analytics_meta.runtime_profile;
SELECT 'analytics_meta.runtime_profile.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.runtime_profile;
SELECT 'analytics_meta.runtime_profile.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.runtime_profile WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.runtime_profile.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.runtime_profile;
SELECT 'analytics_meta.runtime_profile.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.runtime_profile WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.source_registry.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.source_registry;
SELECT 'analytics_meta.source_registry.max_id' AS k, MAX(id) AS v FROM analytics_meta.source_registry;
SELECT 'analytics_meta.source_registry.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.source_registry;
SELECT 'analytics_meta.source_registry.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.source_registry WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.source_registry.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.source_registry;
SELECT 'analytics_meta.source_registry.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.source_registry WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.spark_job_run.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.spark_job_run;
SELECT 'analytics_meta.spark_job_run.max_id' AS k, MAX(id) AS v FROM analytics_meta.spark_job_run;
SELECT 'analytics_meta.spark_job_run.max_started_at' AS k, MAX(started_at) AS v FROM analytics_meta.spark_job_run;
SELECT 'analytics_meta.spark_job_run.inwin_started_at' AS k, COUNT(*) AS v FROM analytics_meta.spark_job_run WHERE started_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.spark_job_run.max_finished_at' AS k, MAX(finished_at) AS v FROM analytics_meta.spark_job_run;
SELECT 'analytics_meta.spark_job_run.inwin_finished_at' AS k, COUNT(*) AS v FROM analytics_meta.spark_job_run WHERE finished_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.sys_user.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.sys_user;
SELECT 'analytics_meta.sys_user.max_id' AS k, MAX(id) AS v FROM analytics_meta.sys_user;
SELECT 'analytics_meta.sys_user.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.sys_user;
SELECT 'analytics_meta.sys_user.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.sys_user WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.t_ckpt_test.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.t_ckpt_test;
SELECT 'analytics_meta.t_ckpt_test.max_id' AS k, MAX(id) AS v FROM analytics_meta.t_ckpt_test;
SELECT 'analytics_meta.t_ckpt_test.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_meta.t_ckpt_test;
SELECT 'analytics_meta.t_ckpt_test.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_meta.t_ckpt_test WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.user_session.rows_total' AS k, COUNT(*) AS v FROM analytics_meta.user_session;
SELECT 'analytics_meta.user_session.max_id' AS k, MAX(id) AS v FROM analytics_meta.user_session;
SELECT 'analytics_meta.user_session.max_expires_at' AS k, MAX(expires_at) AS v FROM analytics_meta.user_session;
SELECT 'analytics_meta.user_session.inwin_expires_at' AS k, COUNT(*) AS v FROM analytics_meta.user_session WHERE expires_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_meta.user_session.max_created_at' AS k, MAX(created_at) AS v FROM analytics_meta.user_session;
SELECT 'analytics_meta.user_session.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_meta.user_session WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_metric.flyway_schema_history.rows_total' AS k, COUNT(*) AS v FROM analytics_metric.flyway_schema_history;
SELECT 'analytics_metric.flyway_schema_history.max_installed_on' AS k, MAX(installed_on) AS v FROM analytics_metric.flyway_schema_history;
SELECT 'analytics_metric.flyway_schema_history.inwin_installed_on' AS k, COUNT(*) AS v FROM analytics_metric.flyway_schema_history WHERE installed_on BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_metric.metric_snapshot.rows_total' AS k, COUNT(*) AS v FROM analytics_metric.metric_snapshot;
SELECT 'analytics_metric.metric_snapshot.max_id' AS k, MAX(id) AS v FROM analytics_metric.metric_snapshot;
SELECT 'analytics_metric.metric_snapshot.max_business_time' AS k, MAX(business_time) AS v FROM analytics_metric.metric_snapshot;
SELECT 'analytics_metric.metric_snapshot.inwin_business_time' AS k, COUNT(*) AS v FROM analytics_metric.metric_snapshot WHERE business_time BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_metric.metric_snapshot.max_data_updated_at' AS k, MAX(data_updated_at) AS v FROM analytics_metric.metric_snapshot;
SELECT 'analytics_metric.metric_snapshot.inwin_data_updated_at' AS k, COUNT(*) AS v FROM analytics_metric.metric_snapshot WHERE data_updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_metric.metric_snapshot.max_published_at' AS k, MAX(published_at) AS v FROM analytics_metric.metric_snapshot;
SELECT 'analytics_metric.metric_snapshot.inwin_published_at' AS k, COUNT(*) AS v FROM analytics_metric.metric_snapshot WHERE published_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_metric.metric_snapshot.max_created_at' AS k, MAX(created_at) AS v FROM analytics_metric.metric_snapshot;
SELECT 'analytics_metric.metric_snapshot.inwin_created_at' AS k, COUNT(*) AS v FROM analytics_metric.metric_snapshot WHERE created_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'analytics_metric.metric_value.rows_total' AS k, COUNT(*) AS v FROM analytics_metric.metric_value;
SELECT 'analytics_metric.metric_value.max_id' AS k, MAX(id) AS v FROM analytics_metric.metric_value;
SELECT 'analytics_metric.metric_value.max_updated_at' AS k, MAX(updated_at) AS v FROM analytics_metric.metric_value;
SELECT 'analytics_metric.metric_value.inwin_updated_at' AS k, COUNT(*) AS v FROM analytics_metric.metric_value WHERE updated_at BETWEEN '2026-09-14 13:50:00' AND '2026-09-14 14:20:00';
SELECT 'run2_source_data_version_rows_3306' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE source_data_version LIKE 'v25it-%';
SELECT 'run2_target_snapshot_rows_3306' AS k, COUNT(*) AS v FROM analytics_meta.pipeline_run WHERE target_snapshot_id = 'S20260901_2';
SELECT 'batch_ings_20260914_rows_3306' AS k, COUNT(*) AS v FROM analytics_meta.ingestion_batch WHERE batch_no LIKE 'ing-20260914%';
SELECT 'v25it_users_3306' AS k, COUNT(*) AS v FROM mysql.user WHERE user LIKE 'v25it%';
SELECT 'metric_snapshot_s2_rows_3306' AS k, COUNT(*) AS v FROM analytics_metric.metric_snapshot WHERE snapshot_id = 'S20260901_2';
SELECT 'meta_flyway_count_3306' AS k, COUNT(*) AS v FROM analytics_meta.flyway_schema_history;
SELECT 'meta_flyway_max_installed_on_3306' AS k, MAX(installed_on) AS v FROM analytics_meta.flyway_schema_history;
